### ISSUE TITLE
can't run code, missing file "data/pairwise_progressGAN.txt"

### ISSUE THREAD

**Issue by BarRozenman** [jesse1029/Fake-Face-Images-Detection-Tensorflow#1]
Hello, I'm trying to run you code but want to test it on images not from the GAN network, but rather images of my own making, I've tried to put the images is the data folder (as specified in the instructions and in the "result/celeba_[GANNAME]" folders but when I try running the code I get an error :

FileNotFoundError: [Errno 2] No such file or directory: 'data/pairwise_progressGAN.txt'

what is this file? I could not find it anywhere and I can't figure out what it suppose to contain,
couldn't  even find  in the google drive of https://github.com/tkarras/progressive_growing_of_gans  
(https://drive.google.com/open?id=0B4qLcYyJmiz0NHFULTdYc05lX0U)

Thank you for this amazing project! any help will be appreciated.

**Comment by jesse1029** [comment]
For ResNet_DeepUD version, you need to prepare the pairwise file list formatted in the following

image_path_1 image_path_2 Same_or_not
image_path_3 image_path_4 Same_or_not
image_path_5 image_path_6 Same_or_not
image_path_7 image_path_8 Same_or_not
...
where image_path_1 is the path to image 1 and image_path_2 is the path to image 2. The Same_or_not is a label indicator when Same_or_not=1 for images 1 and 2 are the same identity and Same_or_not=0 for another case.

**Comment by jesse1029** [comment]
> Hello, I'm trying to run you code but want to test it on images not from the GAN network, but rather images of my own making, I've tried to put the images is the data folder (as specified in the instructions and in the "result/celeba_[GANNAME]" folders but when I try running the code I get an error :
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'data/pairwise_progressGAN.txt'
> 
> what is this file? I could not find it anywhere and I can't figure out what it suppose to contain,
> couldn't even find in the google drive of https://github.com/tkarras/progressive_growing_of_gans
> (https://drive.google.com/open?id=0B4qLcYyJmiz0NHFULTdYc05lX0U)
> 
> Thank you for this amazing project! any help will be appreciated.

For ResNet_DeepUD version, you need to prepare the pairwise file list formatted in the following

image_path_1 image_path_2 Same_or_not
image_path_3 image_path_4 Same_or_not
image_path_5 image_path_6 Same_or_not
image_path_7 image_path_8 Same_or_not
...
where image_path_1 is the path to image 1 and image_path_2 is the path to image 2. The Same_or_not is a label indicator when Same_or_not=1 for images 1 and 2 are the same identity and Same_or_not=0 for another case.
