### ISSUE TITLE
Test with a saved model

### ISSUE THREAD

**Issue by panicwq** [jesse1029/Fake-Face-Images-Detection-Tensorflow#3]
Hello, thank you for sharing your code.
I ran your code and saved the .ckpt model file.
But how do I test with a saved model? And how to use your excellent model...
Can you give me some advice?Thanks a lot！

**Comment by jesse1029** [comment]
> Hello, thank you for sharing your code.
> I ran your code and saved the .ckpt model file.
> But how do I test with a saved model? And how to use your excellent model...
> Can you give me some advice?Thanks a lot！

Hi Panicwq,
The simplest way to test our model is to modify the training code and remove its training codes. Then, the saver.restore(sess, 'path_to_checkpoint_file') can be used to load model. By feeding the image data to our Net, the output (named pred) is the result.

We will also upload the demo code shortly.

**Comment by panicwq** [comment]
> > Hello, thank you for sharing your code.
> > I ran your code and saved the .ckpt model file.
> > But how do I test with a saved model? And how to use your excellent model...
> > Can you give me some advice?Thanks a lot！
> 
> Hi Panicwq,
> The simplest way to test our model is to modify the training code and remove its training codes. Then, the saver.restore(sess, 'path_to_checkpoint_file') can be used to load model. By feeding the image data to our Net, the output (named pred) is the result.
> 
> We will also upload the demo code shortly.

Thank you for your answer.
I will try it!

**Comment by panicwq** [comment]
> > Hello, thank you for sharing your code.
> > I ran your code and saved the .ckpt model file.
> > But how do I test with a saved model? And how to use your excellent model...
> > Can you give me some advice?Thanks a lot！
> 
> Hi Panicwq,
> The simplest way to test our model is to modify the training code and remove its training codes. Then, the saver.restore(sess, 'path_to_checkpoint_file') can be used to load model. By feeding the image data to our Net, the output (named pred) is the result.
> 
> We will also upload the demo code shortly.

Hi！
I changed the code as you suggested, but unfortunately the code doesn't work well. Can you give me some help?
This is my code link.
**https://github.com/panicwq/Fake-Face-Images-Detection-Tensorflow/blob/master/test.py**
Starting from line 240 is my own test code. There is a phenomenon that the progress bar stops moving during running.
can you try it and give me some suggestions?
Thanks!

**Comment by panicwq** [comment]
I have solved this problem~
